### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by jordigulley** [jordigcs/fmod_gd4#5]
- [ ] Add FmodBankResource Importer instead of manually searching the filesystem.
- [ ] Merge FmodEventPlayer
- [ ] Redo tutorials and documentation to fit new changes
- [ ] Optimize and bug fix
- [ ] GDExtension Port
- [ ] Improve editor integration
